# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-27 18:16
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontSlide',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='frontslide_frontslide', serialize=False, to='cms.CMSPlugin')),
                ('image', image_cropping.fields.ImageCropField(upload_to=b'featurebox')),
                ('normal_slide_crop', image_cropping.fields.ImageRatioField(b'image', '1920x1160', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='normal slide crop')),
                ('mobile_slide_crop', image_cropping.fields.ImageRatioField(b'image', '410x314', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='mobile slide crop')),
                ('text', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('page_link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
